authors = ["Sébastien Celles"]
name = "OpenSymbolicRules"
uuid = "63eaa7ab-c3ed-50ea-9f8d-8b348c7d3525"
version = "0.1.0"

[compat]
DomainSets = "0.8.2"
Giac = "0.14.3"
IntervalSets = "0.7.14"
JSON = "1.8.0"
SymbolicUtils = "4.46.6"
julia = "1.10"

[deps]
DomainSets = "5b8099bc-c8ec-5219-889f-1d9e522a28bf"
IntervalSets = "8197267c-284f-5f27-9208-e0e47529a953"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
SymbolicUtils = "d1185830-fcd6-423d-90d6-eec64667417b"

[extensions]
OpenSymbolicRulesGiacExt = "Giac"
OpenSymbolicRulesSymbolicsExt = "Symbolics"

[weakdeps]
Giac = "e4421f97-9838-4fd0-9fa5-94f11373bf78"
Symbolics = "0c5d862f-8b57-4792-8d23-62f2024744c7"

[workspace]
projects = ["test", "docs"]
