[deps]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
LiveServer = "16fef848-5104-11e9-1b77-fb7a48bbb589"
OpenSymbolicRules = "63eaa7ab-c3ed-50ea-9f8d-8b348c7d3525"

[compat]
Documenter = "1"

[sources]
OpenSymbolicRules = {path = ".."}
